### ISSUE TITLE
 Vue-warnings: [vue/require-v-for-key] Elements in iteration expect to have 'v-bind:key' directives.

### ISSUE THREAD

**Issue by Edza** [DCzajkowski/vue-emoji-picker#1]
For:
v-for="(emojiGroup, category) in emojis">
v-for="(emoji, emojiName) in emojiGroup"

[vue/require-v-for-key]
Elements in iteration expect to have 'v-bind:key' directives

I'll try to see if I can fix them myself, and if I can I'll post an update here.

**Comment by DCzajkowski** [comment]
True. It's just a warning and you can totally skip it in this case, but it should be fixed. I'll fix it today. :) Thanks!

**Comment by Edza** [comment]
Thanks. No problem, mate. Definitely not critical.

The problem is I'm using VS Code and it's very ugly red lines that can't be disabled easily. If you are using vetur with VS Code that is the default underlining.

![warns](https://user-images.githubusercontent.com/1269761/41678061-b1c27ac6-74d2-11e8-86f6-f00ff481987d.PNG)

**Comment by DCzajkowski** [comment]
Fixed in: https://github.com/DCzajkowski/vue-emoji-picker/commit/932c0d6c37a65858c8cbbbf902509f1d8bf91128
