### ISSUE TITLE
css is not working

### ISSUE THREAD

**Issue by aditya-developer-intlum** [DCzajkowski/vue-emoji-picker#13]
I read you doc and follow same thing without missing any step but emojis are now available but style is not working .

**Comment by justice47** [comment]
@aditya-developer-intlum please provide minimum repeatable example of the issue.
I've re-created demo page on Codesandbox and it's work alright - [https://codesandbox.io/s/vue-template-w5sbp](https://codesandbox.io/s/vue-template-w5sbp)
