### ISSUE TITLE
Wrapping emoji-picker in transition is not working

### ISSUE THREAD

**Issue by antoine92190** [DCzajkowski/vue-emoji-picker#18]
When trying to wrap the `emoji-picker` slot inside a transition, the emojis are not displayed.

```
<emoji-picker @emoji="insert" :search="search">
    <transition name="fade">
        <div slot="emoji-picker" slot-scope="{ emojis, insert, display }">
        ...
        </div>
    </transition>
</emoji-picker>
```

**Comment by DCzajkowski** [comment]
TBH I have never used the transition component. Does it normally work this way with scoped slots?

**Comment by StuDownie** [comment]
Try adding  ` <transition name="fade" appear>` dies that sort it?

https://vuejs.org/v2/guide/transitions.html#Transitions-on-Initial-Render

**Comment by antoine92190** [comment]
@StuDownie That works thanks!
