### ISSUE TITLE
Add typescript definition

### ISSUE THREAD

**Issue by Edza** [DCzajkowski/vue-emoji-picker#2]
The workaround is with a local type.

All you need is this line:
declare module 'vue-emoji-picker';

Inside a "vue-emoji-picker" folder, which is in the typeRoot.

In tsconfig.json.
 "typeRoots": ["./src/types"],

**Comment by DCzajkowski** [comment]
I'll have a look into that later. Feel free to make a PR if you feel like doing so 😉

**Comment by Edza** [comment]
Thanks. Sure thing, but would I actually have to figure out where to place it from your point of view.

**Comment by Edza** [comment]
Alright, so I forked it, but the "npm run browser-build" is throwing an error:

```
$ npm run browser-build

> vue-emoji-picker@1.0.0 browser-build C:\Users\edza\Desktop\emoji-picker-fork\vue-emoji-picker
> cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o dist/vue-emoji-picker.css ] -e src/main.js | uglifyjs -c warnings=false -m > dist/vue-emoji-picker.js

The system cannot find the path specified.
```

I installed browserify, envify, and uglifyjs globally, but it did not help.

npm run build works fine.

npm run dev:

```
ERROR in ./src/Components/EmojiPicker.vue
Module not found: Error: Can't resolve 'vue' in 'C:\Users\edza\Desktop\emoji-picker-fork\vue-emoji-picker\src\Components'
 @ ./src/Components/EmojiPicker.vue 21:17-31
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js
```


🤔

**Comment by DCzajkowski** [comment]
1. It's connected to you using Windows. Unix-based systems use `/`, whereas Windows uses `\`. I am not sure how to fix that as I don't have a Windows machine at home. Try using some Bash emulator like Git's terminal.
2. For your purposes you don't need to build for a browser. It sucks the `dev` command doesn't work either. But the `build` one should be sufficient.

**Comment by Edza** [comment]
It was a missing dist folder. :D

I am using a bash emulator.

npm run dev still struggling 🤔:

```
ERROR in ./src/Components/EmojiPicker.vue
Module not found: Error: Can't resolve 'vue' in 'C:\Users\edza\Desktop\emoji-picker-fork\vue-emoji-picker\src\Components'
 @ ./src/Components/EmojiPicker.vue 21:17-31
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js
```

**Comment by Edza** [comment]
Can't resolve what's no there. Fixed with: 
npm i -D vue

**Comment by Edza** [comment]
Done.

https://github.com/DCzajkowski/vue-emoji-picker/pull/3

**Comment by DCzajkowski** [comment]
https://github.com/DCzajkowski/vue-emoji-picker/commit/0d1dbaabcf22971fab9aa4c4b5768782c07fbe7d
