### ISSUE TITLE
Exception thrown beginning a search with '+'

### ISSUE THREAD

**Issue by calebbergman** [DCzajkowski/vue-emoji-picker#21]
Typing a plus character '+' in the search box results in, "SyntaxError: Invalid regular expression: /.*+.*/: Nothing to repeat."

**Comment by DCzajkowski** [comment]
Indeed, we should escape any regex-special chars [here](https://github.com/DCzajkowski/vue-emoji-picker/blob/master/src/Components/EmojiPicker.vue#L57) using [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#escaping).

Does anyone want to create a PR with this?

**Comment by DCzajkowski** [comment]
Version 1.0.3 was released, that addresses the issue. Thanks @calebbergman for helping!
