### ISSUE TITLE
How to get list of emojis outside the component?

### ISSUE THREAD

**Issue by trd-warren** [DCzajkowski/vue-emoji-picker#30]
I'm currently working on a feature in which I used the EmojiPicker as a message reaction.
Instead of saving the actual emoji to DB, I wanted the save the `emojiName`.

How can get the list of emojis outside the component?
I wanted to display the emoji in other element using the `emojiName`

**Comment by DCzajkowski** [comment]
Hello, I don't think it's possible, currently the way I bundle the package. You could fetch it from the package's `src/` directory, however.
