### ISSUE TITLE
unicode emojis?

### ISSUE THREAD

**Issue by deep0410** [DCzajkowski/vue-emoji-picker#4]
Are you sure they are unicode emoji's

**Comment by DCzajkowski** [comment]
After putting the [emojis file](https://raw.githubusercontent.com/DCzajkowski/vue-emoji-picker/master/src/emojis.js) into the [Unicode code converter](https://r12a.github.io/app-conversion) every emoji got its unicode code. So I'd say yes. Do you have any problems with them?

**Comment by deep0410** [comment]
When I parse U+1.... it parses to &#x.. and displays it back on the page
but when I use the emoji itself from the the emoji picker and then "save" it/"parse" it, it just shows up as ????

**Comment by DCzajkowski** [comment]
What browser and operating system are you using? Are you storing this data anywhere? Are you using UTF-8?

**Comment by DCzajkowski** [comment]
I am going to close this, as you haven't provided enough data for me to address this issue properly. Feel free to open it back when you have some more information that could help fixing it.
