### ISSUE TITLE
Emoji Win 7 B&W

### ISSUE THREAD

**Issue by mr-stasyuk** [DCzajkowski/vue-emoji-picker#5]
Hi!
I have [this](http://prntscr.com/kax90o) bug with Win 7 and your component. I know, I will have to change Emoji-default object via props "emojiTable", but I can't find acceptable object. Can you help?
Thanks for your emoji-component.

**Comment by DCzajkowski** [comment]
Sure thing! The default object is here: https://github.com/DCzajkowski/vue-emoji-picker/blob/master/src/emojis.js

Just copy-paste it into its own file (like: `emojis.js`) and then just use it:
```vue
<template>
    <textarea v-model="input"></textarea>

    <emoji-picker @emoji="insert" :search="search" :emojiTable="emojiTable">
        <!-- -->
    </emoji-picker>
</template>

<script>
import emojiTable from './emojis.js'

export default {
    data() {
        return {
            emojiTable,
            input: '',
            search: '',
        }
    },
    methods: {
        insert(emoji) {
            this.input += emoji
        },
    },
}
</script>
```

**Comment by mr-stasyuk** [comment]
I probably incorrectly expressed. I need to replace the emoji object with one that I will be compatible with Win 7. Do you understand me?

**Comment by DCzajkowski** [comment]
I understand, but to be clear, I have no clue which emojis are supported on Windows and which are not. You'd need to pick those that are supported, and remove those, that are not

**Comment by DCzajkowski** [comment]
I am going to close this, as different versions of Windows have support for different emojis and I can't help with picking the right ones.

**Comment by dpmango** [comment]
@mr-stasyuk Have you been able to find out any solution? 
Im facing the same issue now and believe the only option is the replace emoji symbols with images

**Comment by DCzajkowski** [comment]
@dpmango There are other emoji pickers that support images, so they may come useful 😉
