### ISSUE TITLE
no emoji...

### ISSUE THREAD

**Issue by jjxs** [DCzajkowski/vue-emoji-picker#7]
![image](https://user-images.githubusercontent.com/25605545/44838783-a981bf00-ac6f-11e8-95f2-2dbe699f4c58.png)

**Comment by DCzajkowski** [comment]
There is this one for example: https://shershen08.github.io/emoji-vue/

**Comment by jjxs** [comment]
HHH,  
I have used it. but It's can not to use
https://github.com/shershen08/emoji-vue/issues/1

**Comment by DCzajkowski** [comment]
Sorry, I can't help then.

**Comment by jjxs** [comment]
thanks
