### ISSUE TITLE
I'm not able to show emoji picker from external button

### ISSUE THREAD

**Issue by jpujol880807** [DCzajkowski/vue-emoji-picker#8]
Hi, let say i want to show the emoji picker content on a modal, to make it compatible with my template, and i wan't to trigger it from a button, but i don't want this button near the emoji picker component. Something like this.
` <div class="modal modal-bottom-right-corner fade" tabindex="-1" role="dialog"  aria-hidden="true" id="emoji-modal">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                                <emoji-picker>
                                         ... Content Here .....
                                </emoji-picker>`

And them from the external button i want to simply show the modal. So i would like to have display: {x: 0, y:0, visible: true} allways Can't place it near emoji-picker because is wraped inside tricky html tags. I can't find a way of modify the slot scoped display property from parent

**Comment by DCzajkowski** [comment]
Could you please provide some example on CodePen or in any other online editor? Any screenshots/drawn concepts would be welcome.

**Comment by n4ss1m** [comment]
I had the same issue displaying emoji list from an external button ( from outside the component ),  and this is how I solved it, I added  `ref="EmojiOpen"` attribute to 'emoji-invoker' slot to became like this : 

```html
<div slot="emoji-invoker" slot-scope="{ events }" v-on="events" ref="EmojiOpen"></div>
```

then added  `@click="$refs.EmojiOpen.click()"` to my external button

```html
<button @click="$refs.EmojiOpen.click()">Display emoji list</button>
```

I hope this will help you!

**Comment by jpujol880807** [comment]
Thanks a lot!!!, that works. Sorry for late response, I'm closing it.

**Comment by DCzajkowski** [comment]
Great it has been resolved 👍
