### ISSUE TITLE
slot-scope broken in Vue 2.6

### ISSUE THREAD

**Issue by Yizen** [DCzajkowski/vue-emoji-picker#9]
Hi, 

I have run into an issue updating to Vue 2.6 : the events are not being passed to the EmojiPicker.

In 2.6, scoped slots have been reworked, and slot-scope has been deprecated.

https://vuejs.org/v2/guide/components-slots.html#Scoped-Slots

This pen demonstrate it : 

https://codepen.io/Yizen/pen/VgrbJO

It is basically the exact clone of your pen, but with Vue upgraded to 2.6

Thank you for this component, and any help you can provide.

**Comment by DCzajkowski** [comment]
To be honest I tried, but I can't get it to work. There must have been a bug introduced, or I can't grasp what is not working :/

**Comment by Yizen** [comment]
My understanding is that v-on on slot was never very well supported. There is a discussion about it here : https://github.com/vuejs/vue/issues/4781

**Comment by DCzajkowski** [comment]
This doesn't seem to be an issue. I have made a click handler and it didn't work either. Maybe there is an issue with passing arrow functions in a template? Frankly, I have no idea how to debug it 😕

**Comment by timroosen** [comment]
We ran into the same issue today with vue 2.6.3. It doesn't seem to be an issue with the slots. The slots are not yet deprecated from v2.6. After some debugging we found out that v-click-outside is called right after the this.toggle() preventing the Emoji picker to show. using e.stopPropagation(); in your click handler should prevent this behaviour.

**Comment by DCzajkowski** [comment]
I can confirm, that it's two things, that need to be changed:
1. The component cannot return an arrow function. It has to be the component's method itself
2. The `.stop` modifier is required (but I have no clue why)

**Comment by Yizen** [comment]
Thanks for the feedback, here is the corrected CodePen for future reference : 

https://codepen.io/Yizen/pen/wNYPVx

`@click="clickEvent"` 

should be corrected for Vue > 2.6 to :

`@click.stop="clickEvent"`

**Comment by LTFENG** [comment]
thanks, I noticed this error too when I update my vue project to 2.6+. 

Would like to ask how do you guys debug for this ? Would like to know how can I think like you guys in order to debug some similar case in future. 

thanks @Yizen, @DCzajkowski  and @timroosen
